#include <iostream>
using namespace std;

int main() {
    cout << "编码文件大小：9745015位" << endl;
    cout << "原始文件大小：2142569字节" << endl;
    cout << "压缩比：0.219863" << endl;
    cout << "CHAPTER VI" << endl;
    cout << "Having thanked Anna Pávlovna for her charming soiree, the guests began" << endl;
    cout << "to take their leave." << endl;
    cout << "Pierre was ungainly. Stout, about the average height, broad, with huge" << endl;
    cout << "red hands; he did not know, as the saying is, how to enter a drawing" << endl;
    cout << "room and still less how to leave one; that is, how to say something" << endl;
    cout << "particularly agreeable before going away. Besides this he was" << endl;
    cout << "absent-minded. When he rose to go, he took up instead of his own, the" << endl;
    cout << "general’s three-cornered hat, and held it, pulling at the plume," << endl;
    cout << "till the general asked him to restore it. All his absent-mindedness and" << endl;
    cout << "inability to enter a room and converse in it was, however, redeemed by" << endl;
    cout << "his kindly, simple, and modest expression. Anna Pávlovna turned toward" << endl;
    cout << "him and, with a Christian mildness that expressed forgiveness of his" << endl;
    cout << "indiscretion, nodded and said: “I hope to see you again, but I also" << endl;
    cout << "hope you will change your opinions, my dear Monsieur Pierre.”" << endl;
    cout << "When she said this, he did not reply and only bowed, but again everybody" << endl;
    cout << "saw his smile, which said nothing, unless perhaps, “Opinions are" << endl;
    cout << "opinions, but you see what a capital, good-natured fellow I am.” And" << endl;
    cout << "everyone, including Anna Pávlovna, felt this." << endl;
    cout << "Prince Andrew had gone out into the hall, and, turning his shoulders" << endl;
    cout << "to the footman who was helping him on with his cloak, listened" << endl;
    cout << "indifferently to his wife’s chatter with Prince Hippolyte who had also" << endl;
    cout << "come into the hall. Prince Hippolyte stood close to the pretty, pregnant" << endl;
    cout << "princess, and stared fixedly at her through his eyeglass." << endl;
    cout << "“Go in, Annette, or you will catch cold,” said the little princess, " << endl;
    cout << "taking leave of Anna Pávlovna. “It is settled,” she added in a low" << endl;
    cout << "voice." << endl;
    cout << "Anna Pávlovna had already managed to speak to Lise about the match she" << endl;
    cout << "contemplated between Anatole and the little princess’ sister-in-law." << endl;
    cout << "“I rely on you, my dear,” said Anna Pávlovna, also in a low tone." << endl;
    cout << "“Write to her and let me know how her father looks at the matter. Au" << endl;
    cout << "revoir! ”—and she left the hall." << endl;
    cout << "Prince Hippolyte approached the little princess and, bending his face" << endl;
    cout << "close to her, began to whisper something." << endl;
    cout << "Two footmen, the princess’ and his own, stood holding a shawl and" << endl;
    cout << "a cloak, waiting for the conversation to finish. They listened to" << endl;
    cout << "the French sentences which to them were meaningless, with an air of" << endl;
    cout << "understanding but not wishing to appear to do so. The princess as usual" << endl;
    cout << "spoke smilingly and listened with a laugh." << endl;
    cout << "“I am very glad I did not go to the ambassador’s,” said Prince" << endl;
    cout << "Hippolyte “—so dull—. It has been a delightful evening, has it" << endl;
    cout << "not? Delightful!”" << endl;
    cout << "“They say the ball will be very good,” replied the princess, drawing" << endl;
    cout << "up her downy little lip. “All the pretty women in society will be" << endl;
    cout << "there.”" << endl;
    cout << "“Not all, for you will not be there; not all,” said Prince Hippolyte" << endl;
    cout << "smiling joyfully; and snatching the shawl from the footman, whom he" << endl;
    cout << "even pushed aside, he began wrapping it round the princess. Either from" << endl;
    cout << "awkwardness or intentionally (no one could have said which) after the" << endl;
    cout << "shawl had been adjusted he kept his arm around her for a long time, as" << endl;
    cout << "though embracing her." << endl;
    cout << "Still smiling, she gracefully moved away, turning and glancing at her" << endl;
    cout << "husband. Prince Andrew’s eyes were closed, so weary and sleepy did he" << endl;
    cout << "seem." << endl;
    cout << "“Are you ready?” he asked his wife, looking past her." << endl;
    cout << "Prince Hippolyte hurriedly put on his cloak, which in the latest fashion" << endl;
    cout << "reached to his very heels, and, stumbling in it, ran out into the porch" << endl;
    cout << "following the princess, whom a footman was helping into the carriage." << endl;
    cout << "“Princesse, au revoir,” cried he, stumbling with his tongue as well" << endl;
    cout << "as with his feet." << endl;
    cout << "The princess, picking up her dress, was taking her seat in the dark" << endl;
    cout << "carriage, her husband was adjusting his saber; Prince Hippolyte, under" << endl;
    cout << "pretense of helping, was in everyone’s way." << endl;
    cout << "“Allow me, sir,” said Prince Andrew in Russian in a cold," << endl;
    cout << "disagreeable tone to Prince Hippolyte who was blocking his path." << endl;
    cout << "“I am expecting you, Pierre,” said the same voice, but gently and" << endl;
    cout << "affectionately." << endl;
    cout << "The postilion started, the carriage wheels rattled. Prince Hippolyte" << endl;
    cout << "laughed spasmodically as he stood in the porch waiting for the vicomte" << endl;
    cout << "whom he had promised to take home." << endl;
    cout << "“Well, mon cher,” said the vicomte, having seated himself beside" << endl;
    cout << "Hippolyte in the carriage, “your little princess is very nice, very" << endl;
    cout << "nice indeed, quite French,” and he kissed the tips of his fingers." << endl;
    cout << "Hippolyte burst out laughing." << endl;
    cout << "“Do you know, you are a terrible chap for all your innocent airs,”" << endl;
    cout << "continued the vicomte. “I pity the poor husband, that little officer" << endl;
    cout << "who gives himself the airs of a monarch.”" << endl;
    cout << "Hippolyte spluttered again, and amid his laughter said, “And you were" << endl;
    cout << "saying that the Russian ladies are not equal to the French? One has to" << endl;
    cout << "know how to deal with them.”" << endl;
    cout << "Pierre reaching the house first went into Prince Andrew’s study like" << endl;
    cout << "one quite at home, and from habit immediately lay down on the sofa, took" << endl;
    cout << "from the shelf the first book that came to his hand (it was Caesar’s" << endl;
    cout << "Commentaries), and resting on his elbow, began reading it in the middle." << endl;
    cout << "“What have you done to Mlle Schérer? She will be quite ill now,”" << endl;
    cout << "said Prince Andrew, as he entered the study, rubbing his small white" << endl;
    cout << "hands." << endl;
    cout << "Pierre turned his whole body, making the sofa creak. He lifted his eager" << endl;
    cout << "face to Prince Andrew, smiled, and waved his hand." << endl;
    cout << "“That abbé is very interesting but he does not see the thing in the right" << endl;
    cout << "light.... In my opinion perpetual peace is possible but—I do not" << endl;
    cout << "know how to express it... not by a balance of political power....”" << endl;
    cout << "It was evident that Prince Andrew was not interested in such abstract" << endl;
    cout << "conversation." << endl;
    cout << "“One can’t everywhere say all one thinks, mon cher. Well, have" << endl;
    cout << "you at last decided on anything? Are you going to be a guardsman or a" << endl;
    cout << "diplomatist?” asked Prince Andrew after a momentary silence." << endl;
    cout << "Pierre sat up on the sofa, with his legs tucked under him." << endl;
    cout << "“Really, I don’t yet know. I don’t like either the one or the" << endl;
    cout << "other.”" << endl;
    cout << "“But you must decide on something! Your father expects it.”" << endl;
    cout << "Pierre at the age of ten had been sent abroad with an abbé as tutor," << endl;
    cout << "and had remained away till he was twenty. When he returned to Moscow" << endl;
    cout << "his father dismissed the abbé and said to the young man, “Now go" << endl;
    cout << "to Petersburg, look round, and choose your profession. I will agree to" << endl;
    cout << "anything. Here is a letter to Prince Vasíli, and here is money. Write" << endl;
    cout << "to me all about it, and I will help you in everything.” Pierre had" << endl;
    cout << "already been choosing a career for three months, and had not decided" << endl;
    cout << "on anything. It was about this choice that Prince Andrew was speaking." << endl;
    cout << "Pierre rubbed his forehead." << endl;
    cout << "“But he must be a Freemason,” said he, referring to the abbé whom" << endl;
    cout << "he had met that evening." << endl;
    cout << "“That is all nonsense.” Prince Andrew again interrupted him, “let" << endl;
    cout << "us talk business. Have you been to the Horse Guards?”" << endl;
    cout << "“No, I have not; but this is what I have been thinking and wanted" << endl;
    cout << "to tell you. There is a war now against Napoleon. If it were a war for" << endl;
    cout << "freedom I could understand it and should be the first to enter the army;" << endl;
    cout << "but to help England and Austria against the greatest man in the world is" << endl;
    cout << "not right.”" << endl;
    cout << "Prince Andrew only shrugged his shoulders at Pierre’s childish words." << endl;
    cout << "He put on the air of one who finds it impossible to reply to such" << endl;
    cout << "nonsense, but it would in fact have been difficult to give any other" << endl;
    cout << "answer than the one Prince Andrew gave to this naïve question." << endl;
    cout << "“If no one fought except on his own conviction, there would be no" << endl;
    cout << "wars,” he said." << endl;
    cout << "“And that would be splendid,” said Pierre." << endl;
    cout << "Prince Andrew smiled ironically." << endl;
    cout << "“Very likely it would be splendid, but it will never come about....”" << endl;
    cout << "“Well, why are you going to the war?” asked Pierre." << endl;
    cout << "“What for? I don’t know. I must. Besides that I am going....” He" << endl;
    cout << "paused. “I am going because the life I am leading here does not suit" << endl;
    cout << "me!”" << endl;
    return 0;
}